Feature/interactive aliases
MarkHedleyJones/dmenu-extended pull request #154
Opened 2022-08-19 23:06 UTC by ZappaBoy

Concerning #152 I added the functionality of executing commands via interactive shell. 
I tried to be as minimally invasive as possible by making few changes and respecting the programming style. 

By default the feature is off but by setting the "interactive_shell" property to "True" in preferences the commands are executed based on the shell set (`$SHELL` env)

This is only a first step as processes launched in the background are not shown to the user but I am working on it in my spare time. 

Anyway I am submitting these changes since I don't know when I can work on them due to my jobs.

Also finished this feature I would like to do a minimum of refactoring always free time permitting.

2022-11-05 09:08 UTC, MarkHedleyJones requested changes
Hi @ZappaBoy,
Thanks so much for creating a PR for your feature request :+1: 
I tested it and it works well.
I left a couple of comments that I'd like you to address, and then I'm happy to merge it into the main branch.

2022-11-05 09:08 UTC, MarkHedleyJones commented on src/dmenu_extended/main.py
> +            shell = os.environ.get("SHELL", "/bin/bash")
Rather than `"/bin/bash"` how about `"/usr/bin/env bash"` to handle compatibility with systems that don't have `bash` under the `/bin` directory.

2022-11-05 09:08 UTC, MarkHedleyJones commented on src/dmenu_extended/main.py
> +    "interactive_shell": False,  # Run commands in interactive mode
For the comment, how about "Run commands in an interactive shell session".

2022-11-05 15:24 UTC, ZappaBoy commented on src/dmenu_extended/main.py
> +            shell = os.environ.get("SHELL", "/bin/bash")
I perfectly agree with you. Changed in #6a6b99d.

2022-11-05 15:26 UTC, ZappaBoy commented on src/dmenu_extended/main.py
> +    "interactive_shell": False,  # Run commands in interactive mode
Changed in 0a30a44f1f006851d3fb45db9c61cd9099a2ce15 .

2022-11-09 17:23 UTC, ZappaBoy commented
I also increased the version string, now the CI pipeline will run successfully.

2022-11-20 20:51 UTC, MarkHedleyJones approved these changes
Looks good to me.
Thanks very much for your patience and time taken to implement this improvement.
I have added your name to the list of Contributions :smile:

2022-11-20 20:51 UTC, merged